### ISSUE TITLE
Discord error: invalid header field value "<TOKEN>" for key Authorization

### ISSUE THREAD

**Issue by skupjoe** [dikey0ficial/dlfm#1]
Hello-

First off, thank you for reviving this project!

I am switching from [DiscordLastfmScrobbler](https://github.com/edvardpotter/DiscordLastfmScrobbler) to this and I updated my config, but I am seeing the following error when I launch the program (Win64):

![image](https://user-images.githubusercontent.com/5000412/145128394-8c633607-a6c7-4635-ad4a-16ae0871abf0.png)

This is my config:
![image](https://user-images.githubusercontent.com/5000412/145128420-ed698359-0627-488e-ac71-316fe917b9cf.png)

**Comment by dikey0ficial** [comment]
Hello. I changed `interval` key to `check_interval` to make more understandable, so you should add `check_` :)

**Comment by skupjoe** [comment]
Hello @dikey0ficial -

I changed `interval` to `check_interval` and the issue persisted.

But I found a fix- it looks like my config was using "LF" and I changed this to "CRLF" and it is working now. Could be this or maybe there was some bad character at the end of my token.

**Comment by dikey0ficial** [comment]
@skupjoe ok... I'll try to fix it in few days

**Comment by dikey0ficial** [comment]
@skupjoe I made an update. Did it fixed it?

**Comment by skupjoe** [comment]
Hi @dikey0ficial -

I am not seeing any recent commit from you, but regardless I cannot reproduce this issue anymore and I think it was a bad character on my end! We are good to close :)

**Comment by dikey0ficial** [comment]
> I am not seeing any recent commit from you

I had some problems with parent commit, but I fixed it :)
