### ISSUE TITLE
Problem with token mode

### ISSUE THREAD

**Issue by iFrez** [dikey0ficial/dlfm#11]
2022/06/14 23:46:39 Config loaded
2022/06/14 23:46:39 Connected to last.fm
2022/06/14 23:46:39 Endless mode! Press `Ctrl+C` to exit
2022/06/14 23:46:40 websocket: close 4004: Authentication failed.
Press enter to close window...

**Comment by dikey0ficial** [comment]
OS, arch and file downloaded?)
P.S. You're not first who has this bug, so I'll try to find reasons od this behaviour and fix them)

**Comment by iFrez** [comment]
Windows 11 22h2 (22621.1), 64 bit, dlfm_windows_amd64 and also dlfm_windows_386, both same result. 
I had old version dlfm_win64 that stops work time ago. Firstly i tried to get new token and its looks different now. Old one mfa.blablabla and new one blablabla:stringlikebase64encoded.

**Comment by ico2k2developer** [comment]
Same/similar problem here.
Windows 10 21H2 Pro, 64 bit, dlfm_windows_amd64.
App mode works perfectly, but token mode produces this output:
`2022/07/09 01:32:01 Config loaded`
`2022/07/09 01:32:01 Connected to last.fm`
`2022/07/09 01:32:01 Endless mode! Press 'Ctrl+C' to exit`
`2022/07/09 01:32:03 [DG0] wsapi.go:552:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string`
`2022/07/09 01:32:03 Authorized and connected to discord`
`2022/07/09 01:32:08 Discord error:  no websocket connection exists`
`2022/07/09 01:32:08 Now playing: Supertramp - A Soapbox Opera`
`2022/07/09 01:32:13 Discord error:  no websocket connection exists`
`2022/07/09 01:32:18 Discord error:  no websocket connection exists`
`2022/07/09 01:32:23 Discord error:  no websocket connection exists`
...and continues like that endlessly.
Hope this is helpful :)

**Comment by dikey0ficial** [comment]
Damn, I just forgot to put pointers 🤦🏼

I'll publish release in few minutes

**Comment by iFrez** [comment]
Token mode still not working 🤷‍♂️ even with new token

**Comment by dikey0ficial** [comment]
> Token mode still not working 🤷‍♂️ even with new token

hm, strange. is it version 4.3.1? what it writes?

**Comment by iFrez** [comment]
> > Token mode still not working 🤷‍♂️ even with new token
> 
> hm, strange. is it version 4.3.1? what it writes?

Yep, 4.3.1. Output same as my first message, "websocket: close 4004: Authentication failed".

**Comment by dikey0ficial** [comment]
> > > Token mode still not working 🤷‍♂️ even with new token
> > 
> > 
> > hm, strange. is it version 4.3.1? what it writes?
> 
> Yep, 4.3.1. Output same as my first message, "websocket: close 4004: Authentication failed".

Code 4004 tells that something wrong with your token ([official discord API docs](https://github.com/discord/discord-api-docs/blob/294ff6ce7c2fc207cf2ef701d49c4f610c42c638/docs/topics/Opcodes_and_Status_Codes.md)), so problem is on your side :)

**Comment by ico2k2developer** [comment]
Both app mode & token mode work perfectly now, so I guess those that still have issues are doing something wrong in their setups because it works fine for me.

**Comment by iFrez** [comment]
I used instruction in readme
![makxsl8Cq1](https://user-images.githubusercontent.com/2266343/179399689-33e79b05-5d1c-479f-ad9a-807eaa8b39a9.png)

**Comment by dikey0ficial** [comment]
> I used instruction in readme ![makxsl8Cq1](https://user-images.githubusercontent.com/2266343/179399689-33e79b05-5d1c-479f-ad9a-807eaa8b39a9.png)

> dQw4w9WgXcQ:...

I really don't know where problem is, but the first part of your token is rickroll ID on youtube :)

**Comment by iFrez** [comment]
I am instal clean discord and now Ctrl+Shift+I not working.  After  adding this line "DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING": true in %appdata%/discord/settings.json. i got this token ;)

**Comment by dikey0ficial** [comment]
> I am instal clean discord and now Ctrl+Shift+I not working. After adding this line "DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING": true in %appdata%/discord/settings.json. i got this token ;)

Ok, this should be easteregg by discord developers :)
try to

**Comment by iFrez** [comment]
DiscordNative.safeStorage.decryptString("encrypted token") 
![image](https://user-images.githubusercontent.com/2266343/179484714-855ea9dc-f00b-45c1-ba17-c1e363695b71.png)

Finally got it.

**Comment by dikey0ficial** [comment]
> DiscordNative.safeStorage.decryptString("encrypted token") ![image](https://user-images.githubusercontent.com/2266343/179484714-855ea9dc-f00b-45c1-ba17-c1e363695b71.png)
> 
> Finally got it.

finally :)

**Comment by dikey0ficial** [comment]
Pinned because it can be useful for people who also has new token type
