### ISSUE TITLE
can u make this for instagram bio updater

### ISSUE THREAD

**Issue by xanabinoid** [dikey0ficial/dlfm#12]
https://github.com/Ezzud/instify
https://github.com/kars0nn/Spotigram
this projects outdated can u make for ig

**Comment by dikey0ficial** [comment]
Sorry, but I can't.
Firstly, I don't use instagram, so I won't be able to test it
Secondly, AFAIK, Meta bans users of third-party tools for their services
At last, it's even blocked in my country (hello, Roskomnadzor!)

Sorry again.
