### ISSUE TITLE
Error `discord-ipc-0: connect: no such file or directory` on v4.0

### ISSUE THREAD

**Issue by skupjoe** [dikey0ficial/dlfm#3]
Thanks for the new features in v4.0! Unfortunately, I am having trouble starting dlfm after pulling the latest version, updating my config (`config.toml`) and building/running:

![image](https://user-images.githubusercontent.com/5000412/150853381-40089c5a-7e1b-46b4-aa68-9d459730acdd.png)

Here is my config:
![image](https://user-images.githubusercontent.com/5000412/150853265-b8889a2d-0281-4708-9a41-754ce94e0826.png)

**Comment by dikey0ficial** [comment]
Which OS do you have? Does work token mode? Can you check are there any files with prefix `discord-ipc-` in `/TMP/` directory? And, maybe, try to reload discord :)

**Comment by dikey0ficial** [comment]
@skupjoe Also, you can try to change "github.com/hugolgst/rich-go" import to "github.com/EpicStep/rich-go" – fork with refactoring and (as i read incommit history) some fixes

**Comment by skupjoe** [comment]
Hi @dikey0ficial . Yes- token mode still works.

Machine info:
```
$ uname -a
Linux skpj-cent-ec2.eskay.dom 3.10.0-862.11.6.el7.x86_64 #1 SMP Fri Aug 10 16:55:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```

Not sure how to reload Discord exactly, but I've definitely updated and restarted it completely between my 3 different clients (2x OSX, 1x Win).

**Comment by skupjoe** [comment]
Nothing in my /tmp or in the folder that I have dlfm in.

I tried building using EpicStep's fork, but I got an error that seems related:
```
# go build
go: finding module for package github.com/EpicStep/rich-go/client
go: downloading github.com/EpicStep/rich-go v0.0.0-20210410114856-ba62d8369611
go: found github.com/EpicStep/rich-go/client in github.com/EpicStep/rich-go v0.0.0-20210410114856-ba62d8369611
# github.com/EpicStep/rich-go/client
/root/go/pkg/mod/github.com/!epic!step/rich-go@v0.0.0-20210410114856-ba62d8369611/client/client.go:15:10: undefined: ipc.IPC
/root/go/pkg/mod/github.com/!epic!step/rich-go@v0.0.0-20210410114856-ba62d8369611/client/client.go:23:12: undefined: ipc.NewIPC
```

**Comment by dikey0ficial** [comment]
As I see, hugolist/rich-go (and EpicStep/rich-go) are abandoned and they works with some issues. I'll try to find alternative or contribute in it)

**Comment by dikey0ficial** [comment]
@scupjoe Have you updated discord since last message? If you had, can you try to turn on app mode again (with last release)? :)

**Comment by dikey0ficial** [comment]
@skupjoe I've just updated dlfm (or rather fork of rich-go) to fix one of readon of this problem. Try, please :)

**Comment by dikey0ficial** [comment]
I found another possible reason. I'll try to fix it :)

**Comment by dikey0ficial** [comment]
@skupjoe I've finally found reason. It's because discord from snap puts his unix socket file into "snap.discord" subdirrectory :)

I've made a fix, soon I'll build and make release

**Comment by skupjoe** [comment]
So far so good, @dikey0ficial . On the new version and working well so far- wlyk if I see anymore of the same
