### ISSUE TITLE
The pipe is being closed error

### ISSUE THREAD

**Issue by bublov** [dikey0ficial/dlfm#4]
Корректно определяется дискорд и трек, но примерно каждые 10 секунд пишется the pipe is being closed и в дискорде в статусе ничего нет.
<details><summary>UPD by @dikey0ficial: Translation</summary>Discord is connecting, app correctly shows which track I'm listening to, but every 10 seconds it prints `the pipe is being closed` and discord status is empty</details>

![image](https://user-images.githubusercontent.com/33785670/151611885-f1980258-8273-40ed-8714-8a3bd1388a81.png)

**Comment by dikey0ficial** [comment]
Я знаю, это проблема библиотеки, использующейся для app mode. она выдаёт эту ошибку не как ошибку, а напрямую выводит её в консоль. как раз смотрю, как это можно поправить.
<details><summary>Translation</summary>I know. It's trouble of library, which I use for app mode. It returns an error not like typical error, but prints it directly in console. I'm searching how can i fix it</details>

**Comment by dikey0ficial** [comment]
Поправил это в обновлении, завтра зарелизю

<details><summary> Translation </summary>Fixed this in update, i'll release it tomorrow </details>
